name: Build and Test

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  pnpm-base-test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: |
            - recursive: false
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: pnpm

      - name: Build
        run: pnpm build
