name: Build and Test
 
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: write

jobs:
  configure:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Pull request auto merge enabler
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        uses: poad/github-pull-request-auto-merge-enable-action@v1.0.5
        with:
          pull_request_id: ${{ github.event.pull_request.node_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          merge_method: SQUASH

  pnpm-base-test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.1
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: pnpm

      - name: Build
        run: pnpm build
