name: enables auto merge

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        type: number
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  configure:
    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    steps:
    - name: Pull request auto merge enabler
      if: github.event_name == 'pull_request'
      uses: poad/github-pull-request-auto-merge-enable-action@v1.0.5
      with:
        pull_request_number: ${{ inputs.pull_request_number }}
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        repository: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}
        merge_method: SQUASH
